### ISSUE TITLE
Windows 10 & ARE: high CPU workload with CIM

### ISSUE THREAD

**Issue by gernus** [asterics/AsTeRICS#116]
If a CIM module (e.g. IMA GPI) is connected to a Windows 10 PC and the ARE is started the CPU workload is about 15%. If there is no CIM module connected, the CPU workload of the ARE is 0% (Demomenu). Seems to be an ARE bug.

**Comment by deinhofer** [comment]
If have reproduced the problem on Win10 1511, in a VirtualBox with the Accelerometer CIM module.

According to Java Mission Control, the high CPU load is in the native call
gnu.io.RXTXPort.readByte

![rxtxportreadbytehighcpuload](https://cloud.githubusercontent.com/assets/4621810/14781710/6a5b0b44-0ae4-11e6-8ad7-c44403f31e14.png)

If you enable the receive timeout for the read operation the CPU load goes down.

```java
RXTXPort port=...
port.enableReceiveTimeout(500);
```

The question is why this is necessary for Win10 and not for the other platforms.
@cristobaldobranco: Do you see any bad side effects if we use enableReceiveTimeout? 
As port.notiveOnDataAvailable is turned on, the subsequent read call should not block but return the data.

**Comment by cristobaldobranco** [comment]
I don't think that there would be a lot of side effects. As incoming data is collected in dataSource queue an occasional waking of the RXTX receive thread should not have any effect on the CIM communication service. Go ahead with the fix ;)
