### ISSUE TITLE
WebACS - repeated warning window if no model is loaded

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/AsTeRICS#154]
If there is no model loaded (especially in an error case, see #153 ) in the ARE, the WebACS repeats to show:

"No model available for download"

It is not very usable afterwards, because this window shows every ~10s for 5 times at once.

No further error is shown by the ARE console.

Platform: Debian Testing, x64

**Comment by deinhofer** [comment]
Moved to https://github.com/asterics/WebACS/issues/10
