### ISSUE TITLE
Java 8 / Windows 10 (Win10)

### ISSUE THREAD

**Issue by eldufdo** [asterics/AsTeRICS#17]
When starting the ARE in Windows 8.1 using the new java 8 release some components can't be loaded by the ARE.
e.g. FS20Sender, Keyboard

With Java 7 it works just fine

**Comment by deinhofer** [comment]
Unfortunately the same for Windows 10 :-(

We will have to update all the manifests for Windows 10 as well. Maybe we can find a better solution to generically add the native libs to the MANIFEST, because this is also necessary for native libs on Linux and Mac.

**Comment by deinhofer** [comment]
**Workaround**
Install Asterics with Java 7 Runtime embedded,because Java 7 does not know anything about Windows10

**Comment by deinhofer** [comment]
According to the OSGI specification you can use an alias ("__win32__" for all windows versions based on x86 or x64) for the osname property in the BundleNativeCode statement of the MANIFEST.

You can download the spec here: https://www.osgi.org/release-3-download/
### Excerpt of the Spec about manually overriding the osname property, chapter 4.9.3
__org.osgi.framework.os.name__
The name of the operating system (OS) of the host computer.
The following table defines a list of OS names. New OS
names are made available on the OSGi web site in the Developers
Zone. Names should be matched case insensitive.
All Framework properties may be defined by the Operator as System properties.
If these properties are not defined as System properties, the Framework
must construct these properties from relevant standard Java System properties.
The alias list is names that have been reported to be returned by certain versions
of the related operating systems. Frameworks should try to convert
these aliases to the canonical OS or processor name. The bundle developer
should use the canonical name in the Bundle-NativeCode manifest header.

Actually the Equinox framework should match to this alias automatically, but it returns 
os.name=windows 10

So manually setting the alias at command line helps :-)

### Workaround
Replace the line actually starting the ARE of start.bat with
```bat
%START_CMD% %JAVA_BIN% %ARE_DEBUG_STRING% %SPLASH_SWITCH% -Dorg.osgi.framework.os.name=win32 -Dosgi.clean=true -Dorg.osgi.framework.bootdelegation=* -Dorg.osgi.framework.system.packages.extra=sun.misc -DAnsi=true -Djava.util.logging.config.file=logging.properties -Deu.asterics.ARE.startModel=%AUTOSTART_MODEL% -Deu.asterics.ARE.ServicesFiles="services.ini;services-windows.ini;%ARE_OPTIONAL_SERVICES_INI%" -jar org.eclipse.osgi_3.6.0.v20100517.jar -configuration %PROFILE_PATH% -console
```

Note the setting of
```bat
-Dorg.osgi.framework.os.name=win32
```

For an up2date list of os names, aliases and processor tags, see:
https://www.osgi.org/developer/specifications/reference/
