### ISSUE TITLE
ARE hotkeys to start/stop model

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS#2]
it would be immportant to add keyboard shortcuts to functions like start / stop model. this is essential if you test models which mess up the standard mouse function so that you cannot stop the model be clicking "stop". 
If the ACS is not connected to the ARE it can get really difficutl to re-gain control over your computer without hotkeys that are always active (also if the ARE window does not have the input focus).
-> We coud add a system-wide keyboard hook (as the keyboard sensor plugin) somewhere in a service class or in the gui class.

**Comment by deinhofer** [comment]
fixed with https://github.com/asterics/AsTeRICS/commit/f2970d201f3a0f59ce80c74819359e9474771f93
