### ISSUE TITLE
spelling misstake in error message when opening invalid file

### ISSUE THREAD

**Issue by stefanstocki** [asterics/AsTeRICS#229]
there is a spelling mistake (see screenshot) -> currend instead of current

![typo](https://user-images.githubusercontent.com/10290425/36664042-cb64a1c8-1ae3-11e8-8cb5-f2e207d0d12e.PNG)

how to get this message:
open the attached model (empty.txt) and acknowledge the first error window with ok and now the window with the erroneous message will pop up.
 
[empty.txt](https://github.com/asterics/AsTeRICS/files/1758004/empty.txt)

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS/commit/6af30998eef9e5e1f9196416c1a67586ae05d8d6
