### ISSUE TITLE
ARE 3.0 is dependent on JRE 8 but JRE 7 is embedded in Setup_AsTeRICS_3_0 

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS#241]
See https://github.com/asterics/asterics-camerainput-cameramouse/issues/1

# Solution
Embed JRE 8 into installer

**Comment by klues** [comment]
should be done with 3.0.1 you uploaded here: https://github.com/asterics/AsTeRICS/releases/tag/v3.0 !? so we can close this, can't we?

**Comment by klues** [comment]
i think it would be good if we link the issues that are resolved with 3.0.1 in the description text in  https://github.com/asterics/AsTeRICS/releases/tag/v3.0 so that it is comprehensible what changed with 3.0.1
