### ISSUE TITLE
KNX plugin: wrong dataformat for dimming with slider

### ISSUE THREAD

**Issue by stefanstocki** [asterics/AsTeRICS#248]
absolute dimming (DPT5.001) with slider is not possible at the moment, as the plugin passes the value as string with comma, but calimero expects a string without comma. (DPT5 is a 8 bit with range  0 - 255 )

![image](https://user-images.githubusercontent.com/10290425/40039891-60f2cfaa-5818-11e8-8bb5-dfdbe3064033.png)

It should be checked whether the respective DPT value is integer or with comma (e.g. temperature)

acs file attached

[KNX.txt](https://github.com/asterics/AsTeRICS/files/2003662/KNX.txt)

**Comment by deinhofer** [comment]
Maybe a good bug to start a contribution :-)
1. Make a new branch
```
Git checkout -b <branchname>
```
2. Fix it
3. Make a pull request
