### ISSUE TITLE
ACS (WebACS) Unify strategy to display help files

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS#252]
This issue is derived from #245.

Obvisously the behaviour of legacy ACS and the WebACS regarding which help files (local, internet, ARE) are displayed is not the same.

This should be changed for both to:
1. If the ACS (WebACS) is not connected to the ARE: Open ACS-Help online (http://asterics.github.io/AsTeRICS/webapps/WebACS/help/index.html?acs&ACS_Basic_Functions.htm)
2. If the ACS (WebACS) is connected to the ARE: Open the ACS-Help of the ARE to reflect the plugin set of the ARE (http://localhost:8081/webapps/WebACS/help/index.html?acs&ACS_Basic_Functions.htm)

**Comment by klues** [comment]
should be solved with:
https://github.com/asterics/WebACS/pull/31/files
and https://github.com/asterics/AsTeRICS/pull/253/files

**Comment by deinhofer** [comment]
Fixed with #253
