### ISSUE TITLE
ACS help does not display correctly

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS#289]
in the current release, the ACS does not display the help system correctly when F1 is pressed and a plugiin is selected. Instead of showing the local help file, the ACS tries to display the online help which does not work when no internet connection is available

**Comment by deinhofer** [comment]
Not related any more, as this is the new strategy to show the online help, which is now a Progressive Web App, which means it's also available offline as soon as it was opened once:

https://www.asterics.eu
