### ISSUE TITLE
LipMouse plugin documentation misses input port documentation

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS#319]
The current plugin documentation of the LipMouse plugin does not have information about the input port
```AtCmd``` and it's supported AT commands.

Please also check if the rest is up2date.

Please directly edit this [file](https://github.com/asterics/AsTeRICS/edit/pre-3.1/Documentation/docs/plugins/sensors/Lipmouse.md) in markdown.

**Comment by ChrisVeigl** [comment]
ok - thanks for the hint! - documentation is up-to-date now
i modified / committed the .htm plugin help because i also needed to change the plugin screenshot etc.
, see: 69bfaeae00a803419bbf45e894a41403f8b29dac

**Comment by deinhofer** [comment]
@ChrisVeigl thanks for updating. We will transfer it to the new format.
@sabicalija could you convert the new contents to .md and move it to the pre-3.1 branch?

Later we should delete all .html files and ensure that only .md can be edited any more.
