### ISSUE TITLE
Installation problems on RP4

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS#324]
On a freshly installed RaspberryPi 4 (with raspbian version 2019-09-26 based on Debian Buster), several problems occur when installing the AsTeRICS .deb installer package:

*) dpkg: dependency problems prevent configuration of asterics-are:
 asterics-are depends on libttspico-utils; however:
  Package libttspico-utils is not installed.
 asterics-are depends on libhidapi-libusb0; however:
  Package libhidapi-libusb0 is not installed.

libttspico-utils is not available in the standard apt sources, but can be installed as outlined here:
https://github.com/alexylem/jarvis/issues/129

after that, the .deb can be installed.

*)  Further problems occur when starting the ARE because of missing constraints/bundles (org.glassfish.grizzly.-httpservice-bundle, java.net.ssl) and missing execution environment (JavaSE-1.6).

This results in unvailability of essential services (e.g. the ARE webserver and WebACS <-> ARE connection).

## CLI protocol

```
On Raspian buster, OpenJDK 11 is default.

pi@raspberrypi:~/Downloads $ sudo dpkg -i asterics-are-4.0.0-alpha1.deb 
Selecting previously unselected package asterics-are.
(Reading database ... 159454 files and directories currently installed.)
Preparing to unpack asterics-are-4.0.0-alpha1.deb ...
Unpacking asterics-are (4.0.0) ...
dpkg: dependency problems prevent configuration of asterics-are:
 asterics-are depends on libttspico-utils; however:
  Package libttspico-utils is not installed.
 asterics-are depends on libhidapi-libusb0; however:
  Package libhidapi-libusb0 is not installed.

dpkg: error processing package asterics-are (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 asterics-are


sudo add-apt-repository ppa:webupd8team/java
did not work, had to install: sudo apt-get install software-properties-common
then, Error: could not find a distribution template for Raspbian/buster
see: https://launchpad.net/~webupd8team/+archive/ubuntu/java


then tried https://github.com/alexylem/jarvis/issues/129
to install libttspico-utils -> worked

then installing the asterics .deb worked!
but: osgi-bundles missing, eg. webserver not running, see screenshots

```
## Screenshots

![image](https://user-images.githubusercontent.com/4621810/66306170-426a1b80-e901-11e9-869c-743774a2a018.png)

![image](https://user-images.githubusercontent.com/4621810/66306224-63327100-e901-11e9-94a6-4cd0a5de304d.png)

![image](https://user-images.githubusercontent.com/4621810/66306254-6ded0600-e901-11e9-8d32-8538adfcf791.png)

**Comment by deinhofer** [comment]
Thanks for reporting!!

## lib dependencies
Regarding libttspico-utils and libhidapi-libusb0 we should update the dependency descriptions or changed to an optional dependency.
I think libusb was needed for the IrTrans access to the IrTrans usb-adapter.

## Java

Are is dependent on Java 8. You are using Java 11.
Try to install it this way: https://www.raspberrypi.org/forums/viewtopic.php?t=248561
or this way: http://www.gridtec.at/java-8-auf-dem-raspberry-pi-installieren-und-testen/

If you need Java 11 for any other reason, you can try the respective PR #323
