### ISSUE TITLE
AsTeRICS homepage: sticky settings panels

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS#341]
if settings panels are opened on the AsTeRICS homepage 
(e.g. solution settings via https://www.asterics.eu/solutions/ or page settings via the settings button)
the settings panels remain sticky on top of the page content (even when the page is changed).
maybe a seperate popup window or another solution to display the settings would be better

**Comment by sabicalija** [comment]
I've opened and copied the issue to https://github.com/asterics/asterics-docs/issues/11.
