### ISSUE TITLE
AsTeRICS homepage: tooltips for solution control buttons

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS#343]
It might be helpful to add tooltips for better usability of the model control button on the AsTeRICS solutions page https://www.asterics.eu/solutions/. 
Although there is a description availabe in the first section the button functions might be unclear if you scroll down to a particular model.
Additionally, tooltips for the hardware requirements ("needed hardware:") would be helpful - to empasize the difference to the supported OS.

**Comment by klues** [comment]
I think these issues belong into this repository: https://github.com/asterics/asterics-docs

**Comment by sabicalija** [comment]
Yes. Thanks anyway. I've copied it to https://github.com/asterics/asterics-docs/issues/10.
