### ISSUE TITLE
combine single letters to words

### ISSUE THREAD

**Issue by punkys** [asterics/AsTeRICS#355]
Hey, I am really new to github, I hope I use it the right way..

I want to create a keyboard with single letters in AsTeRICS as a own grid. The letters should then be combined to words. Finally the words should be read out like words, not like single letters. I couldn't get it done yet.
For the purpose to create a keyboard I also need to configurate an elemente as "space", to devide single words. I think this isn't possible atm.
I would be really grateful for Your help.

Thanks & kind regards
Leo

**Comment by klues** [comment]
Thanks for your issue. Since it's related to AsTeRICS Grid and this is the repository for the AsTeRICS Framework, I'm closing the issue and re-open it in AsTeRICS Grid: https://github.com/asterics/AsTeRICS-Grid/issues/104
