### ISSUE TITLE
Play recorded audio isn't working after the latest version

### ISSUE THREAD

**Issue by fernandafranhan** [asterics/AsTeRICS#361]
Please, after the last update version, all the cells that contains play recorded audio doesn't working.
Sorry, my video is it in portuguese language.
I'm from Brazil.
See when put the button "test" the audio doesn't working, but when put the button "play" the audio is OK.

**Comment by deinhofer** [comment]
Hi,
This sounds indeed to be a bug, but you used the wrong code repository. 
So I moved it to the correct location: https://github.com/asterics/AsTeRICS-Grid/issues/326

Please let's communicate there.
