### ISSUE TITLE
F7 key does not work after GUI elements got focus

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS#56]
the newly added hotkey for stopping a model in the ARE (F7) is not recognized anymore after any GUI element in the main window got the focus (e.g. after a button or slider has been used) - afterwards, also clicking the main window's background / title bar cannot bring back the focus ...

maybe we should think about using the JNI / C++ native hook anyhow, which is also used for the keyboard capture plugin (we talked about moving that to the service layer) - this could be also a good starting point to investigate how we can deal with different native code for Windows and Linux !

**Comment by deinhofer** [comment]
Is now replaced by jnativehook service and supports

starting: F5
pausing: F6
stopping: F7

a model
