### ISSUE TITLE
Keyboard Capture Enhancements

### ISSUE THREAD

**Issue by eldufdo** [asterics/AsTeRICS#57]
Hi all,
i just want to write down the suggestions for the keyboardCapture plugin that arised during the work with our students and a local AT distributor.

1) It's not possible at the moment to receive the events of a keyReleased event if two buttons are pressed at the same time. E.g. To control a RC car with the keyboard it's necessary to sample the state of the cursor keys. When the user wants to drive straight forward he presses and holds the UP key and the keycode output sends the value 38. Now the user wants to drive a left curve and additionally presses and holds the left cursor key. Now the keyboard capture plugin displays 37. Next the user releases the left key to continue driving straight forward. But now the KeyboardCapture plugin outputs 0 although the up key is still pressed.

I think we need the possibility to get the pressed and released events for specific keyboard buttons in the plugin.

2) One user wanted to overwrite the functionality of the F1 key and use it to type "Strg-A". All other keyboard keys should act normal. The problem now is that with the blockEvents property disabled Windows will always open the help file when F1 was pressed and then type Strg-A. If blocked Events is enabled the F1 key will work as intended, but all other keys won't. One idea was to connect the keybaordCapture keycode output to a MathEvaluator with the following formula (a != 112) * a and connect the output to the keyboard Plugin. But this obviously leads to an endless loop.

I think a mode where only a defined set (the ones to be captured) of keys are blocked would be nice.

I don't have the ressources to implement this stuff at the moment but maybe someone else has.

Ideas to solve any of the problems directly in a model without a code change in the plugins would be very nice ;)

cheers david

**Comment by deinhofer** [comment]
should work now: KeyCapture plugin
