### ISSUE TITLE
start_debug overwrites loader.ini

### ISSUE THREAD

**Issue by eldufdo** [asterics/AsTeRICS#63]
I just modified the loader.ini to load a new experimental plugin I'm working on.
After starting the ARE with the start_debug the script has overwritten my loader.ini with the backup file created last time I used it with the webservice parameter.

Deleting the backup file works, but it's not the most intuitive solution for new users I guess

**Comment by ChrisVeigl** [comment]
An idea would be to pass an argument to the install - methods in the BundleManager class which read the loader.ini and servics.ini files. (these files are not required by the OSGI standard - we could select alternative filenames for different configurations via commandline options.)
