### ISSUE TITLE
ACS: move component fly away!!!!

### ISSUE THREAD

**Issue by eldufdo** [asterics/AsTeRICS#72]
When moving a component around with the mouse it sometimes happens (especially if the user consumed various psychodelic drugs before using the ACS) that the component starts to move away from the mouse cursor and the user can't catch it anymore.
I think the bug is somewhere around the quite messy on_left_down and on_left_move event handlers!

**Comment by ChrisVeigl** [comment]
changing int to float removed the drift ;-)

**Comment by deinhofer** [comment]
yeah, veigl for bughunter of the month! :-)

-------- Ursprüngliche Nachricht --------
Von: Chris Veigl <notifications@github.com> 
Datum:24.02.2015  11:39  (GMT+01:00) 
An: asterics/AsTeRICS <AsTeRICS@noreply.github.com> 
Betreff: Re: [AsTeRICS] ACS: move component fly away!!!! (#72) 

changing int to float removed the drift ;-)
