### ISSUE TITLE
ACS: mixup of property keys in setRuntimePropertyValue when editing properties and confirming with Enter

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS#85]
The properties in the ACS editor get mixed up, if editing is done in the following order:
1) Select plugin (Oscilloscope)
2) Select property frequency
3) Change value, tab out: a new frequency is set
4) Select property frequency again
5) Change value, press enter: a new amplitude is set

See the following picture and debug statements:
![image](https://cloud.githubusercontent.com/assets/4621810/8083765/48b8078e-0f87-11e5-92c3-bde2479d2028.png)

**Comment by eldufdo** [comment]
hopefully fixed, please test the new ACS.exe in the bin dir.
