### ISSUE TITLE
Plugin "EditBox": no copy&paste possible -> error

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/AsTeRICS#89]
If you want to copy&paste the EditBox plugin, the ACS shows the error:

"Error loading component EditBox.1.2: The model does not fit to the component collection description. Undefined properties were reset to the default values"

The copied instance shows up all properties (after re-selecting it, see #88) as a normal inserted one.

BUT: there is no corresponding GUI applet in the GUI overview.

**Comment by deinhofer** [comment]
Danke David!! :+1:
