### ISSUE TITLE
Eliminate need for autostart.ini model

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS#93]
autostart.ini model is used to indicate the default autostart model.
But if no autostart.ini file is available, the first model found should be autostarted.

**Comment by kingcole** [comment]
hm...are you sure about starting the first model found? I feel it would make more sense to start no model at all, when no autostart is found...

**Comment by deinhofer** [comment]
At least if there is just one model it makes sense to autostart it.
Maybe for several models found, leave it like before.
